# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('consumable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_types.ConsumableGeneric', verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='FixedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('I', 'in-use'), ('A', 'available')], default='A', max_length=1)),
                ('notes', models.CharField(max_length=120)),
                ('fixed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_types.FixedGeneric', verbose_name='type')),
            ],
            options={
                'verbose_name_plural': 'Fixed Items',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=25)),
                ('license_number', models.CharField(max_length=50)),
                ('license_count', models.IntegerField(default=1)),
                ('in_use', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LifespanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('I', 'in-use'), ('A', 'available'), ('D', 'damaged')], default='A', max_length=1)),
                ('notes', models.CharField(max_length=120)),
                ('lifespan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_types.LifespanGeneric', verbose_name='type')),
            ],
            options={
                'verbose_name_plural': 'Lifespan Items',
            },
        ),
    ]
