# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_types', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='in_use',
        ),
    ]
