# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_types', '0002_remove_license_in_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='license_count',
        ),
    ]
