# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generic_types.LocationType', verbose_name='type')),
                ('stocked', smart_selects.db_fields.ChainedManyToManyField(chained_field='location_type', chained_model_field='stocked_in', to='generic_types.ConsumableGeneric')),
            ],
        ),
    ]
